### ISSUE TITLE
Tracking API to 'Feature Complete'

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/go-keypairs#1]
## Tracking Feature Complete

Milestone 1: JOSE Debugger

- [x] Generate Private Keys
  - [x] PKIX + RSA + EC
- [x] Generate Public Keys from Private Keys
  - [x] PKIK for EC
  - [x] PKCS1 for RSA
  - [ ] PKIX for RSA Public
- [x] Create JWT with specified JSON payload
- [x] Verify self-signed JWT 
- [x] Verify self-signed JOSE (uncompressed jwt)

Milestone 2: Public Keystore

- [ ] Publish public key 
- [ ] Associate public key with account
    - and thereby with email
- [ ] Verify email
- [ ] Grant access to email address in token (debug for browser)
- [ ] Handle public jwk `exp`

Milestone 3: Social Login

- [ ] Protect against clickjacking with window === top and some such
- [ ] Add SSO / social login
    - [ ] Google
    - [ ] Apple
    - [ ] Microsoft
    - [ ] Facebook
    - [ ] Github
